// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class PaMVC
{
    static readonly AdministrationClass s_Administration = new AdministrationClass();
    public static AdministrationClass Administration { get { return s_Administration; } }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdministrationClass
    {
        public readonly string Name = "Administration";
        public ControlPannel.Areas.Administration.Controllers.AccountController Account = new ControlPannel.Areas.Administration.Controllers.T4MVC_AccountController();
        public ControlPannel.Areas.Administration.Controllers.DefaultController Default = new ControlPannel.Areas.Administration.Controllers.T4MVC_DefaultController();
        public ControlPannel.Areas.Administration.Controllers.RoleController Role = new ControlPannel.Areas.Administration.Controllers.T4MVC_RoleController();
        public ControlPannel.Areas.Administration.Controllers.UserController User = new ControlPannel.Areas.Administration.Controllers.T4MVC_UserController();
        public T4MVC.Administration.EditorTemplatesController EditorTemplates = new T4MVC.Administration.EditorTemplatesController();
        public T4MVC.Administration.EmailsController Emails = new T4MVC.Administration.EmailsController();
        public T4MVC.Administration.RazorHelpersController RazorHelpers = new T4MVC.Administration.RazorHelpersController();
        public T4MVC.Administration.SharedController Shared = new T4MVC.Administration.SharedController();
        public T4MVC.Administration.UserMailerController UserMailer = new T4MVC.Administration.UserMailerController();
    }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace PaLinks
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Admin {
            public const string UrlPath = "~/Scripts/Admin";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string _DS_Store = Url(".DS_Store");
            public static readonly string application_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/application.min.js") ? Url("application.min.js") : Url("application.js");
            public static readonly string application_blank_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/application_blank.min.js") ? Url("application_blank.min.js") : Url("application_blank.js");
            public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class charts {
                public const string UrlPath = "~/Scripts/Admin/charts";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string _DS_Store = Url(".DS_Store");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class full {
                    public const string UrlPath = "~/Scripts/Admin/charts/full";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string animated_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/animated_1.min.js") ? Url("animated_1.min.js") : Url("animated_1.js");
                    public static readonly string animated_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/animated_2.min.js") ? Url("animated_2.min.js") : Url("animated_2.js");
                    public static readonly string animated_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/animated_3.min.js") ? Url("animated_3.min.js") : Url("animated_3.js");
                    public static readonly string auto_empty_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/auto_empty.min.js") ? Url("auto_empty.min.js") : Url("auto_empty.js");
                    public static readonly string auto_filled_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/auto_filled.min.js") ? Url("auto_filled.min.js") : Url("auto_filled.js");
                    public static readonly string donut_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/donut.min.js") ? Url("donut.min.js") : Url("donut.js");
                    public static readonly string horizontal_bars_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/horizontal_bars.min.js") ? Url("horizontal_bars.min.js") : Url("horizontal_bars.js");
                    public static readonly string multiple_axes_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/multiple_axes.min.js") ? Url("multiple_axes.min.js") : Url("multiple_axes.js");
                    public static readonly string pie_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/pie.min.js") ? Url("pie.min.js") : Url("pie.js");
                    public static readonly string pie_full_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/pie_full.min.js") ? Url("pie_full.min.js") : Url("pie_full.js");
                    public static readonly string simple_graph_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/simple_graph.min.js") ? Url("simple_graph.min.js") : Url("simple_graph.js");
                    public static readonly string vertical_bars_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/vertical_bars.min.js") ? Url("vertical_bars.min.js") : Url("vertical_bars.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class widgets {
                    public const string UrlPath = "~/Scripts/Admin/charts/widgets";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string _DS_Store = Url(".DS_Store");
                    public static readonly string filled_blue_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/filled_blue.min.js") ? Url("filled_blue.min.js") : Url("filled_blue.js");
                    public static readonly string filled_green_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/filled_green.min.js") ? Url("filled_green.min.js") : Url("filled_green.js");
                    public static readonly string filled_red_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/filled_red.min.js") ? Url("filled_red.min.js") : Url("filled_red.js");
                    public static readonly string updating_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/updating_1.min.js") ? Url("updating_1.min.js") : Url("updating_1.js");
                    public static readonly string updating_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/updating_2.min.js") ? Url("updating_2.min.js") : Url("updating_2.js");
                    public static readonly string updating_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/updating_3.min.js") ? Url("updating_3.min.js") : Url("updating_3.js");
                }
            
            }
        
            public static readonly string common_scripts_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/common.scripts.min.js") ? Url("common.scripts.min.js") : Url("common.scripts.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class globalize {
                public const string UrlPath = "~/Scripts/Admin/globalize";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string globalize_culture_de_DE_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/globalize.culture.de-DE.min.js") ? Url("globalize.culture.de-DE.min.js") : Url("globalize.culture.de-DE.js");
                public static readonly string globalize_culture_ja_JP_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/globalize.culture.ja-JP.min.js") ? Url("globalize.culture.ja-JP.min.js") : Url("globalize.culture.ja-JP.js");
                public static readonly string globalize_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/globalize.min.js") ? Url("globalize.min.js") : Url("globalize.js");
            }
        
            public static readonly string jqueryval_default_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jqueryval.default.min.js") ? Url("jqueryval.default.min.js") : Url("jqueryval.default.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class plugins {
                public const string UrlPath = "~/Scripts/Admin/plugins";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string _DS_Store = Url(".DS_Store");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class charts {
                    public const string UrlPath = "~/Scripts/Admin/plugins/charts";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string _DS_Store = Url(".DS_Store");
                    public static readonly string excanvas_min_js = Url("excanvas.min.js");
                    public static readonly string flot_animator_min_js = Url("flot.animator.min.js");
                    public static readonly string flot_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/flot.min.js") ? Url("flot.min.js") : Url("flot.js");
                    public static readonly string flot_orderbars_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/flot.orderbars.min.js") ? Url("flot.orderbars.min.js") : Url("flot.orderbars.js");
                    public static readonly string flot_pie_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/flot.pie.min.js") ? Url("flot.pie.min.js") : Url("flot.pie.js");
                    public static readonly string flot_resize_min_js = Url("flot.resize.min.js");
                    public static readonly string flot_time_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/flot.time.min.js") ? Url("flot.time.min.js") : Url("flot.time.js");
                    public static readonly string sparkline_min_js = Url("sparkline.min.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class forms {
                    public const string UrlPath = "~/Scripts/Admin/plugins/forms";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string _DS_Store = Url(".DS_Store");
                    public static readonly string autosize_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autosize.min.js") ? Url("autosize.min.js") : Url("autosize.js");
                    public static readonly string inputlimit_min_js = Url("inputlimit.min.js");
                    public static readonly string inputmask_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/inputmask.min.js") ? Url("inputmask.min.js") : Url("inputmask.js");
                    public static readonly string listbox_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/listbox.min.js") ? Url("listbox.min.js") : Url("listbox.js");
                    public static readonly string multiselect_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/multiselect.min.js") ? Url("multiselect.min.js") : Url("multiselect.js");
                    public static readonly string select2_min_js = Url("select2.min.js");
                    public static readonly string switch_min_js = Url("switch.min.js");
                    public static readonly string tags_min_js = Url("tags.min.js");
                    public static readonly string uniform_min_js = Url("uniform.min.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class uploader {
                        public const string UrlPath = "~/Scripts/Admin/plugins/forms/uploader";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                        public static readonly string plupload_full_min_js = Url("plupload.full.min.js");
                        public static readonly string plupload_queue_min_js = Url("plupload.queue.min.js");
                    }
                
                    public static readonly string validate_min_js = Url("validate.min.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class wysihtml5 {
                        public const string UrlPath = "~/Scripts/Admin/plugins/forms/wysihtml5";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                        public static readonly string toolbar_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/toolbar.min.js") ? Url("toolbar.min.js") : Url("toolbar.js");
                        public static readonly string wysihtml5_min_js = Url("wysihtml5.min.js");
                    }
                
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class @interface {
                    public const string UrlPath = "~/Scripts/Admin/plugins/interface";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string _DS_Store = Url(".DS_Store");
                    public static readonly string collapsible_min_js = Url("collapsible.min.js");
                    public static readonly string colorpicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/colorpicker.min.js") ? Url("colorpicker.min.js") : Url("colorpicker.js");
                    public static readonly string datatables_min_js = Url("datatables.min.js");
                    public static readonly string daterangepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/daterangepicker.min.js") ? Url("daterangepicker.min.js") : Url("daterangepicker.js");
                    public static readonly string fancybox_min_js = Url("fancybox.min.js");
                    public static readonly string fullcalendar_min_js = Url("fullcalendar.min.js");
                    public static readonly string hover_dropdown_min_js = Url("hover_dropdown.min.js");
                    public static readonly string jgrowl_min_js = Url("jgrowl.min.js");
                    public static readonly string moment_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment.min.js") ? Url("moment.min.js") : Url("moment.js");
                    public static readonly string mousewheel_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/mousewheel.min.js") ? Url("mousewheel.min.js") : Url("mousewheel.js");
                    public static readonly string prettify_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/prettify.min.js") ? Url("prettify.min.js") : Url("prettify.js");
                    public static readonly string tabletools_min_js = Url("tabletools.min.js");
                    public static readonly string timepicker_min_js = Url("timepicker.min.js");
                }
            
            }
        
        }
    
        public static readonly string jquery_3_1_0_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.0.intellisense.min.js") ? Url("jquery-3.1.0.intellisense.min.js") : Url("jquery-3.1.0.intellisense.js");
        public static readonly string jquery_3_1_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.0.min.js") ? Url("jquery-3.1.0.min.js") : Url("jquery-3.1.0.js");
        public static readonly string jquery_3_1_0_min_js = Url("jquery-3.1.0.min.js");
        public static readonly string jquery_3_1_0_min_map = Url("jquery-3.1.0.min.map");
        public static readonly string jquery_3_1_0_slim_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.0.slim.min.js") ? Url("jquery-3.1.0.slim.min.js") : Url("jquery-3.1.0.slim.js");
        public static readonly string jquery_3_1_0_slim_min_js = Url("jquery-3.1.0.slim.min.js");
        public static readonly string jquery_3_1_0_slim_min_map = Url("jquery-3.1.0.slim.min.map");
        public static readonly string jquery_1_10_0_min_js = Url("jquery.1.10.0.min.js");
        public static readonly string jquery_ui_1_11_4_min_js = Url("jquery.ui.1.11.4.min.js");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.unobtrusive.ajax.min.js") ? Url("jquery.unobtrusive.ajax.min.js") : Url("jquery.unobtrusive.ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive.ajax.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        public static readonly string PersianDatePicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/PersianDatePicker.min.js") ? Url("PersianDatePicker.min.js") : Url("PersianDatePicker.js");
        public static readonly string PersianDatePicker_min_js = Url("PersianDatePicker.min.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_matchmedia_addListener_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/respond.matchmedia.addListener.min.js") ? Url("respond.matchmedia.addListener.min.js") : Url("respond.matchmedia.addListener.js");
        public static readonly string respond_matchmedia_addListener_min_js = Url("respond.matchmedia.addListener.min.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
        public static readonly string icons_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/icons.min.css") ? Url("icons.min.css") : Url("icons.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            public const string UrlPath = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string _DS_Store = Url(".DS_Store");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class colorpicker {
                public const string UrlPath = "~/Content/images/colorpicker";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string alpha_png = Url("alpha.png");
                public static readonly string hue_png = Url("hue.png");
                public static readonly string saturation_png = Url("saturation.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class flags {
                public const string UrlPath = "~/Content/images/flags";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string _DS_Store = Url(".DS_Store");
                public static readonly string english_png = Url("english.png");
                public static readonly string german_png = Url("german.png");
                public static readonly string hungarian_png = Url("hungarian.png");
                public static readonly string spanish_png = Url("spanish.png");
                public static readonly string ukrainian_png = Url("ukrainian.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class forms {
                public const string UrlPath = "~/Content/images/forms";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string add_files_png = Url("add_files.png");
                public static readonly string check_png = Url("check.png");
                public static readonly string check_white_png = Url("check_white.png");
                public static readonly string checkbox_png = Url("checkbox.png");
                public static readonly string checkbox_blue_png = Url("checkbox_blue.png");
                public static readonly string checkbox_dark_png = Url("checkbox_dark.png");
                public static readonly string checkbox_green_png = Url("checkbox_green.png");
                public static readonly string checkbox_red_png = Url("checkbox_red.png");
                public static readonly string choice_png = Url("choice.png");
                public static readonly string choice_white_png = Url("choice_white.png");
                public static readonly string clear_results_png = Url("clear_results.png");
                public static readonly string dropdown_arrow_down_png = Url("dropdown_arrow_down.png");
                public static readonly string dropdown_arrow_up_png = Url("dropdown_arrow_up.png");
                public static readonly string radio_png = Url("radio.png");
                public static readonly string radio_blue_png = Url("radio_blue.png");
                public static readonly string radio_dark_png = Url("radio_dark.png");
                public static readonly string radio_green_png = Url("radio_green.png");
                public static readonly string radio_red_png = Url("radio_red.png");
                public static readonly string select_multiple_add_png = Url("select_multiple_add.png");
                public static readonly string spinner_bottom_png = Url("spinner_bottom.png");
                public static readonly string spinner_top_png = Url("spinner_top.png");
                public static readonly string switch_handler_png = Url("switch_handler.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @interface {
                public const string UrlPath = "~/Content/images/interface";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string _DS_Store = Url(".DS_Store");
                public static readonly string arrow_left_png = Url("arrow_left.png");
                public static readonly string arrow_right_png = Url("arrow_right.png");
                public static readonly string breadcrumb_home_png = Url("breadcrumb_home.png");
                public static readonly string datepicker_trigger_png = Url("datepicker_trigger.png");
                public static readonly string filter_png = Url("filter.png");
                public static readonly string lightbox_overlay_png = Url("lightbox_overlay.png");
                public static readonly string loader_gif = Url("loader.gif");
                public static readonly string minus_png = Url("minus.png");
                public static readonly string nav_arrow_left_png = Url("nav_arrow_left.png");
                public static readonly string nav_arrow_right_png = Url("nav_arrow_right.png");
                public static readonly string plupload_done_png = Url("plupload_done.png");
                public static readonly string plupload_error_png = Url("plupload_error.png");
                public static readonly string plupload_remove_png = Url("plupload_remove.png");
                public static readonly string plupload_title_png = Url("plupload_title.png");
                public static readonly string plus_png = Url("plus.png");
                public static readonly string slider_handle_png = Url("slider_handle.png");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class tables {
                    public const string UrlPath = "~/Content/images/interface/tables";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string filter_png = Url("filter.png");
                    public static readonly string sort_asc_png = Url("sort_asc.png");
                    public static readonly string sort_asc_disabled_png = Url("sort_asc_disabled.png");
                    public static readonly string sort_both_png = Url("sort_both.png");
                    public static readonly string sort_desc_png = Url("sort_desc.png");
                    public static readonly string sort_desc_disabled_png = Url("sort_desc_disabled.png");
                }
            
                public static readonly string typing_gif = Url("typing.gif");
                public static readonly string user_arrow_default_png = Url("user_arrow_default.png");
                public static readonly string user_arrow_hover_png = Url("user_arrow_hover.png");
                public static readonly string user_menu_arrow_png = Url("user_menu_arrow.png");
                public static readonly string vertical_arrows_png = Url("vertical_arrows.png");
                public static readonly string zoom_png = Url("zoom.png");
            }
        
            public static readonly string logo_png = Url("logo.png");
            public static readonly string logo_dark_png = Url("logo_dark.png");
        }
    
        public static readonly string londinium_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/londinium-theme.min.css") ? Url("londinium-theme.min.css") : Url("londinium-theme.css");
        public static readonly string PagedList_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/PagedList.min.css") ? Url("PagedList.min.css") : Url("PagedList.css");
        public static readonly string PersianDatePicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/PersianDatePicker.min.css") ? Url("PersianDatePicker.min.css") : Url("PersianDatePicker.css");
        public static readonly string PersianDatePicker_min_css = Url("PersianDatePicker.min.css");
        public static readonly string styles_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/styles.min.css") ? Url("styles.min.css") : Url("styles.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class Admin 
            {
                public static partial class charts 
                {
                    public static partial class full 
                    {
                        public static class Assets
                        {
                            public const string animated_1_js = "~/Scripts/Admin/charts/full/animated_1.js"; 
                            public const string animated_2_js = "~/Scripts/Admin/charts/full/animated_2.js"; 
                            public const string animated_3_js = "~/Scripts/Admin/charts/full/animated_3.js"; 
                            public const string auto_empty_js = "~/Scripts/Admin/charts/full/auto_empty.js"; 
                            public const string auto_filled_js = "~/Scripts/Admin/charts/full/auto_filled.js"; 
                            public const string donut_js = "~/Scripts/Admin/charts/full/donut.js"; 
                            public const string horizontal_bars_js = "~/Scripts/Admin/charts/full/horizontal_bars.js"; 
                            public const string multiple_axes_js = "~/Scripts/Admin/charts/full/multiple_axes.js"; 
                            public const string pie_js = "~/Scripts/Admin/charts/full/pie.js"; 
                            public const string pie_full_js = "~/Scripts/Admin/charts/full/pie_full.js"; 
                            public const string simple_graph_js = "~/Scripts/Admin/charts/full/simple_graph.js"; 
                            public const string vertical_bars_js = "~/Scripts/Admin/charts/full/vertical_bars.js"; 
                        }
                    }
                    public static partial class widgets 
                    {
                        public static class Assets
                        {
                            public const string filled_blue_js = "~/Scripts/Admin/charts/widgets/filled_blue.js"; 
                            public const string filled_green_js = "~/Scripts/Admin/charts/widgets/filled_green.js"; 
                            public const string filled_red_js = "~/Scripts/Admin/charts/widgets/filled_red.js"; 
                            public const string updating_1_js = "~/Scripts/Admin/charts/widgets/updating_1.js"; 
                            public const string updating_2_js = "~/Scripts/Admin/charts/widgets/updating_2.js"; 
                            public const string updating_3_js = "~/Scripts/Admin/charts/widgets/updating_3.js"; 
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static partial class globalize 
                {
                    public static class Assets
                    {
                        public const string globalize_culture_de_DE_js = "~/Scripts/Admin/globalize/globalize.culture.de-DE.js"; 
                        public const string globalize_culture_ja_JP_js = "~/Scripts/Admin/globalize/globalize.culture.ja-JP.js"; 
                        public const string globalize_js = "~/Scripts/Admin/globalize/globalize.js"; 
                    }
                }
                public static partial class plugins 
                {
                    public static partial class charts 
                    {
                        public static class Assets
                        {
                            public const string excanvas_min_js = "~/Scripts/Admin/plugins/charts/excanvas.min.js"; 
                            public const string flot_animator_min_js = "~/Scripts/Admin/plugins/charts/flot.animator.min.js"; 
                            public const string flot_js = "~/Scripts/Admin/plugins/charts/flot.js"; 
                            public const string flot_orderbars_js = "~/Scripts/Admin/plugins/charts/flot.orderbars.js"; 
                            public const string flot_pie_js = "~/Scripts/Admin/plugins/charts/flot.pie.js"; 
                            public const string flot_resize_min_js = "~/Scripts/Admin/plugins/charts/flot.resize.min.js"; 
                            public const string flot_time_js = "~/Scripts/Admin/plugins/charts/flot.time.js"; 
                            public const string sparkline_min_js = "~/Scripts/Admin/plugins/charts/sparkline.min.js"; 
                        }
                    }
                    public static partial class forms 
                    {
                        public static partial class uploader 
                        {
                            public static class Assets
                            {
                                public const string plupload_full_min_js = "~/Scripts/Admin/plugins/forms/uploader/plupload.full.min.js"; 
                                public const string plupload_queue_min_js = "~/Scripts/Admin/plugins/forms/uploader/plupload.queue.min.js"; 
                            }
                        }
                        public static partial class wysihtml5 
                        {
                            public static class Assets
                            {
                                public const string toolbar_js = "~/Scripts/Admin/plugins/forms/wysihtml5/toolbar.js"; 
                                public const string wysihtml5_min_js = "~/Scripts/Admin/plugins/forms/wysihtml5/wysihtml5.min.js"; 
                            }
                        }
                        public static class Assets
                        {
                            public const string autosize_js = "~/Scripts/Admin/plugins/forms/autosize.js"; 
                            public const string inputlimit_min_js = "~/Scripts/Admin/plugins/forms/inputlimit.min.js"; 
                            public const string inputmask_js = "~/Scripts/Admin/plugins/forms/inputmask.js"; 
                            public const string listbox_js = "~/Scripts/Admin/plugins/forms/listbox.js"; 
                            public const string multiselect_js = "~/Scripts/Admin/plugins/forms/multiselect.js"; 
                            public const string select2_min_js = "~/Scripts/Admin/plugins/forms/select2.min.js"; 
                            public const string switch_min_js = "~/Scripts/Admin/plugins/forms/switch.min.js"; 
                            public const string tags_min_js = "~/Scripts/Admin/plugins/forms/tags.min.js"; 
                            public const string uniform_min_js = "~/Scripts/Admin/plugins/forms/uniform.min.js"; 
                            public const string validate_min_js = "~/Scripts/Admin/plugins/forms/validate.min.js"; 
                        }
                    }
                    public static partial class @interface 
                    {
                        public static class Assets
                        {
                            public const string collapsible_min_js = "~/Scripts/Admin/plugins/interface/collapsible.min.js"; 
                            public const string colorpicker_js = "~/Scripts/Admin/plugins/interface/colorpicker.js"; 
                            public const string datatables_min_js = "~/Scripts/Admin/plugins/interface/datatables.min.js"; 
                            public const string daterangepicker_js = "~/Scripts/Admin/plugins/interface/daterangepicker.js"; 
                            public const string fancybox_min_js = "~/Scripts/Admin/plugins/interface/fancybox.min.js"; 
                            public const string fullcalendar_min_js = "~/Scripts/Admin/plugins/interface/fullcalendar.min.js"; 
                            public const string hover_dropdown_min_js = "~/Scripts/Admin/plugins/interface/hover_dropdown.min.js"; 
                            public const string jgrowl_min_js = "~/Scripts/Admin/plugins/interface/jgrowl.min.js"; 
                            public const string moment_js = "~/Scripts/Admin/plugins/interface/moment.js"; 
                            public const string mousewheel_js = "~/Scripts/Admin/plugins/interface/mousewheel.js"; 
                            public const string prettify_js = "~/Scripts/Admin/plugins/interface/prettify.js"; 
                            public const string tabletools_min_js = "~/Scripts/Admin/plugins/interface/tabletools.min.js"; 
                            public const string timepicker_min_js = "~/Scripts/Admin/plugins/interface/timepicker.min.js"; 
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                    public const string application_js = "~/Scripts/Admin/application.js"; 
                    public const string application_blank_js = "~/Scripts/Admin/application_blank.js"; 
                    public const string bootstrap_min_js = "~/Scripts/Admin/bootstrap.min.js"; 
                    public const string common_scripts_js = "~/Scripts/Admin/common.scripts.js"; 
                    public const string jqueryval_default_js = "~/Scripts/Admin/jqueryval.default.js"; 
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string jquery_3_1_0_intellisense_js = "~/Scripts/jquery-3.1.0.intellisense.js"; 
                public const string jquery_3_1_0_js = "~/Scripts/jquery-3.1.0.js"; 
                public const string jquery_3_1_0_min_js = "~/Scripts/jquery-3.1.0.min.js"; 
                public const string jquery_3_1_0_slim_js = "~/Scripts/jquery-3.1.0.slim.js"; 
                public const string jquery_3_1_0_slim_min_js = "~/Scripts/jquery-3.1.0.slim.min.js"; 
                public const string jquery_1_10_0_min_js = "~/Scripts/jquery.1.10.0.min.js"; 
                public const string jquery_ui_1_11_4_min_js = "~/Scripts/jquery.ui.1.11.4.min.js"; 
                public const string jquery_unobtrusive_ajax_js = "~/Scripts/jquery.unobtrusive.ajax.js"; 
                public const string jquery_unobtrusive_ajax_min_js = "~/Scripts/jquery.unobtrusive.ajax.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_8_3_js = "~/Scripts/modernizr-2.8.3.js"; 
                public const string PersianDatePicker_js = "~/Scripts/PersianDatePicker.js"; 
                public const string PersianDatePicker_min_js = "~/Scripts/PersianDatePicker.min.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_matchmedia_addListener_js = "~/Scripts/respond.matchmedia.addListener.js"; 
                public const string respond_matchmedia_addListener_min_js = "~/Scripts/respond.matchmedia.addListener.min.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class images 
            {
                public static partial class colorpicker 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class flags 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class forms 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class @interface 
                {
                    public static partial class tables 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string font_awesome_min_css = "~/Content/font-awesome.min.css";
                public const string icons_css = "~/Content/icons.css";
                public const string londinium_theme_css = "~/Content/londinium-theme.css";
                public const string PagedList_css = "~/Content/PagedList.css";
                public const string PersianDatePicker_css = "~/Content/PersianDatePicker.css";
                public const string PersianDatePicker_min_css = "~/Content/PersianDatePicker.min.css";
                public const string styles_css = "~/Content/styles.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


