#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ControlPannel;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administration/Views/UserMailer/_Layout.cshtml")]
    public partial class _Areas_Administration_Views_UserMailer__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Administration_Views_UserMailer__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\n<html>\n<head>\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(@">
    <!--[if lt IE 9]>
      <script src=""https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.js""></script>
    <![endif]-->

    <!--[if lte IE 6]><script src=""/Scripts/warning.js""></script><script>window.onload=function()
    {e(""js/ie6/"");}</script><![endif]-->

    <title> </title>
</head>
<body>
    <header>
    </header>

    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Areas\Administration\Views\UserMailer\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n\n    <footer");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\n    </footer>\n</body>\n</html>");

        }
    }
}
#pragma warning restore 1591
