#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using BlogPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Blog/Views/AdminComment/Edit.cshtml")]
    public partial class _Areas_Blog_Views_AdminComment_Edit_cshtml : System.Web.Mvc.WebViewPage<BlogPlugin.ViewModel.EditCommentModel>
    {
        public _Areas_Blog_Views_AdminComment_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<center>\r\n    \r\n");

            
            #line 7 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
     using (Html.BeginForm(BMVC.Blog.AdminComment.ActionNames.Edit, BMVC.Blog.AdminComment.Name, new { area = BMVC.Blog.Name }, FormMethod.Post))
    {

        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\'row\'");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\'box-title\'");

WriteLiteral(" style=\"margin-bottom:1%\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\'comments-form\'");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" action=\"#\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 17 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
                   Write(Html.TextAreaFor(model => model.Body, new { style = "height:90px;width:450px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 18 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div><br />\r\n                    <div");

WriteLiteral(" style=\"direction:ltr;text-align:left\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"postComment\"");

WriteLiteral(" value=\'ارسال بفرمایید\'");

WriteLiteral(" class=\'btn btn-custom btn-red btn-medium btn-large-text\'");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n");

            
            #line 26 "..\..\Areas\Blog\Views\AdminComment\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</center>");

        }
    }
}
#pragma warning restore 1591
