#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using BlogPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Blog/Views/AdminComment/ReplyShow.cshtml")]
    public partial class _Areas_Blog_Views_AdminComment_ReplyShow_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<BlogPlugin.Models.PostComment>>
    {
        public _Areas_Blog_Views_AdminComment_ReplyShow_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
 foreach (var item in Model)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-actions no-color\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" style=\"font-weight:bold;color:darkorange;\"");

WriteLiteral(">");

            
            #line 8 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
                                                    Write(Html.ConvertToPersianDateTime(item.CreatedOn));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <br />\r\n        <span>");

            
            #line 10 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
         Write(Html.DisplayFor(a => item.Body));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <br />\r\n        <div");

WriteLiteral(" style=\"direction:ltr;\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
             using (Html.BeginForm(BMVC.Blog.AdminComment.ActionNames.DeleteConfirmed, BMVC.Blog.AdminComment.Name, new { id = item.Id }))
            {
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"حذف\"");

WriteLiteral(" class=\"btn btn-default left\"");

WriteLiteral(" />\r\n");

            
            #line 17 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 20 "..\..\Areas\Blog\Views\AdminComment\ReplyShow.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
