#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using PortfoiloPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Portfoilo/Views/AdminPortfoilo/Create.cshtml")]
    public partial class _Areas_Portfoilo_Views_AdminPortfoilo_Create_cshtml : System.Web.Mvc.WebViewPage<PortfoiloPlugin.ViewModel.AddOrUpdatePortfoilo>
    {
        public _Areas_Portfoilo_Views_AdminPortfoilo_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
  
    Layout = "~/Views/Themes/Admin/_LayoutAdmin.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- Right labels -->\r\n");

            
            #line 7 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
 using (Html.BeginForm(PoMVC.Portfoilo.AdminPortfoilo.ActionNames.Create, PoMVC.Portfoilo.AdminPortfoilo.Name, new { area = PoMVC.Portfoilo.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "addblog", enctype = "multipart/form-data" }))

{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral("><h6");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-paragraph-right2\"");

WriteLiteral("></i> ایجاد نمونه کار</h6></div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 17 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
               Write(Html.LabelFor(a => a.Title, new { @class = "col-sm-2 control-label text-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 19 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.TextBoxFor(a => a.Title, new { @class = "form-control", @placeholder = "placeholder" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
               Write(Html.LabelFor(a => a.Slug, new { @class = "col-sm-2 control-label text-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 25 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.TextBoxFor(a => a.Slug, new { @class = "form-control", @placeholder = "placeholder" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
               Write(Html.LabelFor(m => m.Summary, new { @class = "col-md-2 control-label text-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.TextAreaFor(m => m.Summary, new { style = "height:300px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 33 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Summary, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
               Write(Html.LabelFor(m => m.Body, new { @class = "col-md-2 control-label text-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.TextAreaFor(m => m.Body, new { style = "height:300px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 40 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Body, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                    <label");

WriteLiteral(" class=\"checkbox-inline pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 46 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.CheckBoxFor(a => a.Published, new { @class = "switch switch-large", @type = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
                   Write(Html.LabelFor(a => a.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </label>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"InputFile\"");

WriteLiteral(" class=\"col-md-2 control-label text-right\"");

WriteLiteral(">بارگذاری عکس</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"styled\"");

WriteLiteral(" name=\"InputFile\"");

WriteLiteral(" id=\"InputFile\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-actions text-right\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ثبت اطلاعات\"");

WriteLiteral(" class=\"btn btn-primary pull-left\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 63 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<!-- /right labels -->\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 67 "..\..\Areas\Portfoilo\Views\AdminPortfoilo\Create.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3442), Tuple.Create("\"", 3478)
, Tuple.Create(Tuple.Create("", 3448), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ckeditor/ckeditor.js")
, 3448), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3502), Tuple.Create("\"", 3536)
, Tuple.Create(Tuple.Create("", 3508), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ckeditor/config.js")
, 3508), false)
);

WriteLiteral(@"></script>
    <script>
        var roxyFileman = '../../../Scripts/RoxyFileManager/index.html';
        $(function () {
            if (CKEDITOR.instances['Body']) {
                CKEDITOR.remove(CKEDITOR.instances['Body']);
            }

            CKEDITOR.replace('Body', {
                filebrowserBrowseUrl: roxyFileman,
                filebrowserImageBrowseUrl: roxyFileman + '?type=image',
                removeDialogTabs: 'link:upload;image:upload'
            });
            CKEDITOR.replace('Summary', {
                filebrowserBrowseUrl: roxyFileman,
                filebrowserImageBrowseUrl: roxyFileman + '?type=image',
                removeDialogTabs: 'link:upload;image:upload'
            });

        });
    </script>

");

});

        }
    }
}
#pragma warning restore 1591
