#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using PortfoiloPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Portfoilo/Views/AdminCategory/Create.cshtml")]
    public partial class _Areas_Portfoilo_Views_AdminCategory_Create_cshtml : System.Web.Mvc.WebViewPage<PortfoiloPlugin.ViewModel.AddOrUpdateCategory>
    {
        public _Areas_Portfoilo_Views_AdminCategory_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
  
    Layout = "~/Views/Themes/Admin/_LayoutAdmin.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- Right labels -->\r\n");

            
            #line 7 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
 using (Html.BeginForm(PoMVC.Portfoilo.AdminCategory.ActionNames.Create, PoMVC.Portfoilo.AdminCategory.Name, new { area = PoMVC.Portfoilo.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "addblog", enctype = "multipart/form-data" }))

{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral("><h6");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-paragraph-right2\"");

WriteLiteral("></i> ایجاد بلاگ</h6></div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 17 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
               Write(Html.LabelFor(a => a.Name, new { @class = "col-sm-2 control-label text-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 19 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
                   Write(Html.TextBoxFor(a => a.Name, new { @class = "form-control", @placeholder = "placeholder" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
               Write(Html.LabelFor(a => a.Slug, new { @class = "col-sm-2 control-label text-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 25 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
                   Write(Html.TextBoxFor(a => a.Slug, new { @class = "form-control", @placeholder = "placeholder" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                    <label");

WriteLiteral(" class=\"checkbox-inline pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
                   Write(Html.CheckBoxFor(a => a.IsActive, new { @class = "switch switch-large", @type = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 33 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
                   Write(Html.LabelFor(a => a.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </label>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"InputFile\"");

WriteLiteral(" class=\"col-sm-4 control-label\"");

WriteLiteral(">بارگذاری عکس</label>\r\n                    <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"styled\"");

WriteLiteral(" name=\"InputFile\"");

WriteLiteral(" id=\"InputFile\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-actions text-right\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ثبت اطلاعات\"");

WriteLiteral(" class=\"btn btn-primary left\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 49 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<!-- /right labels -->\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 53 "..\..\Areas\Portfoilo\Views\AdminCategory\Create.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
