#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using BlogPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Blog/Views/AdminPost/Delete.cshtml")]
    public partial class _Areas_Blog_Views_AdminPost_Delete_cshtml : System.Web.Mvc.WebViewPage<BlogPlugin.Models.BlogPost>
    {
        public _Areas_Blog_Views_AdminPost_Delete_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("    ");

            
            #line 3 "..\..\Areas\Blog\Views\AdminPost\Delete.cshtml"
     using (Html.BeginForm(BMVC.Blog.AdminPost.ActionNames.DeleteConfirmed, BMVC.Blog.AdminPost.Name))
    {
        
            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Blog\Views\AdminPost\Delete.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Blog\Views\AdminPost\Delete.cshtml"
                                


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-actions no-color\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" style=\"font-weight:bold;color:darkorange;\"");

WriteLiteral(">آیا از حذف این محتوا مطمئنید ؟</span>\r\n            <br />\r\n            <span>در " +
"صورت حذف محتوا تمامی اطلاعات مرتبط با آن حذف خواهد شد</span>\r\n            <br />" +
"\r\n            <div");

WriteLiteral(" style=\"direction:ltr;\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"حذف\"");

WriteLiteral(" class=\"btn btn-default left\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n");

            
            #line 16 "..\..\Areas\Blog\Views\AdminPost\Delete.cshtml"
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
