#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Administration\Views\User\Create.cshtml"
    using AradCms.Core.Helpers;
    
    #line default
    #line hidden
    using ControlPannel;
    
    #line 3 "..\..\Areas\Administration\Views\User\Create.cshtml"
    using ControlPannel.Areas.Administration.Views.RazorHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administration/Views/User/Create.cshtml")]
    public partial class _Areas_Administration_Views_User_Create_cshtml : System.Web.Mvc.WebViewPage<AradCms.Core.ViewModel.User.AddUserViewModel>
    {
        public _Areas_Administration_Views_User_Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\Administration\Views\User\Create.cshtml"
  
    ViewBag.Title = "درج کاربر";
    Layout = "~/Views/Themes/Admin/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Areas\Administration\Views\User\Create.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Administration\Views\User\Create.cshtml"
         using (Html.BeginForm(PaMVC.Administration.User.ActionNames.Create, PaMVC.Administration.User.Name, new { area = PaMVC.Administration.Name }, FormMethod.Post, new { User = "form", @class = "form-horizontal", autocomplete = "off", id = "createUserForm" }))
        {
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Administration\Views\User\Create.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Administration\Views\User\Create.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>مشخصات کاربر</strong>\r\n                </div>\r\n   " +
"             <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#requiredInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">مشخصات ضروری</a>\r\n                        </li>\r\n                        <li>\r\n " +
"                           <a");

WriteLiteral(" href=\"#optionalInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">مشخصات اختیاری</a>\r\n                        </li>\r\n                        <li>\r" +
"\n                            <a");

WriteLiteral(" href=\"#permissions\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">دسترسی های</a>\r\n                        </li>\r\n                        <li>\r\n   " +
"                         <a");

WriteLiteral(" href=\"#settings\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">تنظیمات کاربری</a>\r\n                        </li>\r\n                        <li>\r" +
"\n                            <a");

WriteLiteral(" href=\"#roles\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">گروه های کاربری</a>\r\n                        </li>\r\n                    </ul>\r\n " +
"                   <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"requiredInfo\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 39 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 41 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.TextBoxFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 42 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 46 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 48 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.TextBoxFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 49 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 53 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 55 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.FormControlPasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 56 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 60 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.NameForShow, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 62 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.TextBoxFor(m => m.NameForShow));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 63 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.ValidationMessageFor(m => m.NameForShow, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"optionalInfo\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 69 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.AdministratorComment, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 71 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.TextAreaFor(m => m.AdministratorComment, new { @rows = 3, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 72 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.ValidationMessageFor(m => m.AdministratorComment, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 76 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.GooglePlusId, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 78 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.TextBoxFor(m => m.GooglePlusId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 79 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.ValidationMessageFor(m => m.GooglePlusId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 83 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.FaceBookId, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 85 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.TextBoxFor(m => m.FaceBookId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 86 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.ValidationMessageFor(m => m.FaceBookId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 90 "..\..\Areas\Administration\Views\User\Create.cshtml"
                           Write(Html.LabelFor(m => m.AvatarFileName, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(" dir=\"ltr\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" id=\"AvatarImage\"");

WriteLiteral(" name=\"AvatarImage\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" accept=\"image/*\"");

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"permissions\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 97 "..\..\Areas\Administration\Views\User\Create.cshtml"
                       Write(CheckBoxListBuilder.CheckBoxList("PermissionIds", ViewBag.Permissions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"settings\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 103 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.CheckBoxFor(m => m.IsBanned, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 104 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.LabelFor(m => m.IsBanned, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 107 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.CheckBoxFor(m => m.CanChangeProfilePicture, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 108 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.LabelFor(m => m.CanChangeProfilePicture, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 111 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.CheckBoxFor(m => m.CanUploadFile, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 112 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.LabelFor(m => m.CanUploadFile, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 115 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.CheckBoxFor(m => m.CanModifyFirsAndLastName, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 116 "..\..\Areas\Administration\Views\User\Create.cshtml"
                               Write(Html.LabelFor(m => m.CanModifyFirsAndLastName, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"roles\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 121 "..\..\Areas\Administration\Views\User\Create.cshtml"
                       Write(CheckBoxListBuilder.CheckBoxList("RoleIds", ViewBag.Roles));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'createUserForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                                ثبت کاربر جدید\r\n                            </" +
"button>\r\n                        </div>\r\n                    </div>\r\n           " +
"     </div>\r\n            </div>\r\n");

            
            #line 135 "..\..\Areas\Administration\Views\User\Create.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 139 "..\..\Areas\Administration\Views\User\Create.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n            warningBeforeLoad();\r\n      " +
"      makeUploadFile(\"AvatarImage\");\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
