#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SliderPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sliders/Views/SliderWidget/SliderShow.cshtml")]
    public partial class _Areas_Sliders_Views_SliderWidget_SliderShow_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<SliderPlugin.ViewModel.AddOrUpdate>>
    {
        public _Areas_Sliders_Views_SliderWidget_SliderShow_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"
 if (Model != null)
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"banner-container revolution\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"banner\"");

WriteLiteral(">\r\n            <ul>\r\n");

            
            #line 8 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"
                
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"
                 foreach (var item in Model)
                {


            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" data-transition=\"fade\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 321), Tuple.Create("\"", 369)
, Tuple.Create(Tuple.Create("", 327), Tuple.Create<System.Object, System.Int32>(Href("~/Uploads/SiteMedia/Slider/")
, 327), false)
            
            #line 12 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"
, Tuple.Create(Tuple.Create("", 354), Tuple.Create<System.Object, System.Int32>(item.ImagePath
            
            #line default
            #line hidden
, 354), false)
);

WriteLiteral(" style=\"background-color: #65676e;\"");

WriteLiteral(" alt=\"اسلایدر\"");

WriteLiteral(" />\r\n                        <div");

WriteLiteral(" class=\"caption sfb upper white-bg \"");

WriteLiteral(" data-x=\"850\"");

WriteLiteral(" data-y=\"120\"");

WriteLiteral(" data-speed=\"900\"");

WriteLiteral(" data-start=\"800\"");

WriteLiteral(" data-easing=\"Sine.easeOut\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 14 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"
                       Write(Html.DisplayFor(a => item.TitleOne));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"caption sfb lower white-bg \"");

WriteLiteral(" data-x=\"850\"");

WriteLiteral(" data-y=\"180\"");

WriteLiteral(" data-speed=\"900\"");

WriteLiteral(" data-start=\"1300\"");

WriteLiteral(" data-easing=\"Sine.easeOut\"");

WriteLiteral(">");

            
            #line 16 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"
                                                                                                                                                    Write(Html.DisplayFor(a => item.TitleTwo));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div");

WriteLiteral(" class=\"caption sfb lower white-bg \"");

WriteLiteral(" data-x=\"850\"");

WriteLiteral(" data-y=\"240\"");

WriteLiteral(" data-speed=\"900\"");

WriteLiteral(" data-start=\"1800\"");

WriteLiteral(" data-easing=\"Sine.easeOut\"");

WriteLiteral(">");

            
            #line 17 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"
                                                                                                                                                    Write(Html.DisplayFor(a => item.TitleThree));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </li>\r\n");

            
            #line 19 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n            <div");

WriteLiteral(" class=\"tp-bannertimer tp-bottom\"");

WriteLiteral("></div>\r\n        </div>\r\n        <!-- /.banner -->\r\n    </div>\r\n");

            
            #line 26 "..\..\Areas\Sliders\Views\SliderWidget\SliderShow.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
