#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using FormPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/FormPlug/Views/Widget/CreateOrder.cshtml")]
    public partial class _Areas_FormPlug_Views_Widget_CreateOrder_cshtml : System.Web.Mvc.WebViewPage<FormPlugin.ViewModel.AddOrUpdateOrderForm>
    {
        public _Areas_FormPlug_Views_Widget_CreateOrder_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
  
    Layout = "~/Views/Shared/_LayoutDetail.cshtml";
    ViewBag.Title = "فرم سفارش محصول";


            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- Right labels -->\r\n");

            
            #line 8 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
 using (Html.BeginForm(FoMVC.FormPlug.Widget.ActionNames.CreateOrder, FoMVC.FormPlug.Widget.Name, new { area = FoMVC.FormPlug.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "addOrder", enctype = "multipart/form-data" }))

{
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default \"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-heading \"");

WriteLiteral(">\r\n            <strong>سفارش دهید</strong>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 20 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.NoAutoCompleteTextBoxFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
           Write(Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.NoAutoCompleteTextBoxFor(m => m.Phone));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <span>");

            
            #line 31 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
                 Write(Html.LabelFor(m => m.Phone, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.NoAutoCompleteTextBoxFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
           Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.NoAutoCompleteTextBoxFor(m => m.Website));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 45 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Website, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
           Write(Html.LabelFor(m => m.Website, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 53 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.NoAutoCompleteTextBoxFor(m => m.Company));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Company, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
           Write(Html.LabelFor(m => m.Company, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.NoAutoCompleteTextBoxFor(m => m.Address));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 62 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                ");

            
            #line 64 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
           Write(Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 69 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.NoAutoCompleteTextBoxFor(m => m.Subject));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 70 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Subject, "", new { @class = "text-danger commenttext" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                ");

            
            #line 72 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
           Write(Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <span>");

            
            #line 75 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
                 Write(Html.LabelFor(m => m.Description, new { @class = "labeltext" }));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 77 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.TextAreaFor(m => m.Description, new { @class = "commentfullText", style = "height:300px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 78 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
               Write(Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'addOrder\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn-block pull-left\"");

WriteLiteral(">\r\n                    ثبت  محتوا\r\n                </button>\r\n            </div>\r" +
"\n        </div>\r\n    </div>\r\n");

            
            #line 88 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
}

            
            #line default
            #line hidden
DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 90 "..\..\Areas\FormPlug\Views\Widget\CreateOrder.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n            warningBeforeLoad();\r\n      " +
"  })\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
