#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using CommonInfoPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteInfo/Views/Widget/Contactus.cshtml")]
    public partial class _Areas_SiteInfo_Views_Widget_Contactus_cshtml : System.Web.Mvc.WebViewPage<AradCms.Core.ViewModel.Site.AddOrUpdateSiteInfo>
    {
        public _Areas_SiteInfo_Views_Widget_Contactus_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\SiteInfo\Views\Widget\Contactus.cshtml"
  
    ViewBag.Title = "تماس با ما";
    Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"light-wrapper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container inner\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"map\"");

WriteLiteral(">\r\n            <iframe");

WriteAttribute("src", Tuple.Create(" src=\"", 257), Tuple.Create("\"", 283)
            
            #line 10 "..\..\Areas\SiteInfo\Views\Widget\Contactus.cshtml"
, Tuple.Create(Tuple.Create("", 263), Tuple.Create<System.Object, System.Int32>(Model.GooglemapCode
            
            #line default
            #line hidden
, 263), false)
);

WriteLiteral(" width=\"100%\"");

WriteLiteral(" height=\"450\"");

WriteLiteral(" frameborder=\"0\"");

WriteLiteral(" scrolling=\"no\"");

WriteLiteral(" marginheight=\"0\"");

WriteLiteral(" marginwidth=\"0\"");

WriteLiteral(" allowfullscreen></iframe>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"divide50\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                <h1");

WriteLiteral(" class=\"post-title\"");

WriteLiteral(">درباره ما</h1>\r\n                <p>");

            
            #line 16 "..\..\Areas\SiteInfo\Views\Widget\Contactus.cshtml"
              Write(Html.Raw(Model.SiteContact));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <div");

WriteLiteral(" class=\"divide20\"");

WriteLiteral("></div>\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Areas\SiteInfo\Views\Widget\Contactus.cshtml"
           Write(Html.Action(InfMVC.SiteInfo.Widget.ActionNames.Contact, InfMVC.SiteInfo.Widget.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <!-- /.form-container -->\r\n            </div>\r\n            <!--" +
" /.col -->\r\n            <aside");

WriteLiteral(" class=\"col-sm-4 sidebar lp20\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"sidebox widget\"");

WriteLiteral(">\r\n                    <strong>آدرس</strong>\r\n                    <p>راه های تماس" +
" با ما به شرح زیر می باشد.</p>\r\n                    <address>\r\n                 " +
"       <p>");

            
            #line 27 "..\..\Areas\SiteInfo\Views\Widget\Contactus.cshtml"
                      Write(Html.DisplayFor(a => Model.SiteAddress));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        <abbr");

WriteLiteral(" title=\"Phone\"");

WriteLiteral(">P:</abbr> ");

            
            #line 28 "..\..\Areas\SiteInfo\Views\Widget\Contactus.cshtml"
                                                 Write(Html.DisplayFor(a => Model.SitePhone));

            
            #line default
            #line hidden
WriteLiteral(" <br>\r\n                    </address>\r\n                </div>\r\n                <!" +
"-- /.widget -->\r\n            </aside>\r\n            <!-- /.col -->\r\n        </div" +
">\r\n        <!-- /.row -->\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Areas\SiteInfo\Views\Widget\Contactus.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
