#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using CommonInfoPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteInfo/Views/Widget/ContactFooter.cshtml")]
    public partial class _Areas_SiteInfo_Views_Widget_ContactFooter_cshtml : System.Web.Mvc.WebViewPage<AradCms.Core.ViewModel.Site.AddOrUpdateSiteInfo>
    {
        public _Areas_SiteInfo_Views_Widget_ContactFooter_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"widget\"");

WriteLiteral(">\r\n        <strong");

WriteLiteral(" class=\"widget-title upper\"");

WriteLiteral(">در تماس باشید</strong>\r\n        <p>");

            
            #line 5 "..\..\Areas\SiteInfo\Views\Widget\ContactFooter.cshtml"
      Write(Html.Raw(Model.SiteContact));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n        <div");

WriteLiteral(" class=\"contact-info\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"icon-location\"");

WriteLiteral("></i> ");

            
            #line 7 "..\..\Areas\SiteInfo\Views\Widget\ContactFooter.cshtml"
                                     Write(Html.DisplayFor(a => Model.SiteAddress));

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n            <i");

WriteLiteral(" class=\"icon-phone\"");

WriteLiteral("></i>");

            
            #line 8 "..\..\Areas\SiteInfo\Views\Widget\ContactFooter.cshtml"
                                 Write(Html.DisplayFor(a => Model.SitePhone));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
