#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using CommonInfoPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteInfo/Views/Widget/FooterAboute.cshtml")]
    public partial class _Areas_SiteInfo_Views_Widget_FooterAboute_cshtml : System.Web.Mvc.WebViewPage<AradCms.Core.ViewModel.Site.AddOrUpdateSiteInfo>
    {
        public _Areas_SiteInfo_Views_Widget_FooterAboute_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"widget\"");

WriteLiteral(">\r\n        <strong");

WriteLiteral(" class=\"widget-title upper\"");

WriteLiteral(">درباره ما</strong>\r\n");

WriteLiteral("        ");

            
            #line 5 "..\..\Areas\SiteInfo\Views\Widget\FooterAboute.cshtml"
   Write(Html.Raw(Model.SiteAboute));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"divide5\"");

WriteLiteral("></div>\r\n        <ul");

WriteLiteral(" class=\"social\"");

WriteLiteral(">\r\n\r\n            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-s-twitter\"");

WriteLiteral("></i></a></li>\r\n            <li><a");

WriteLiteral(" href=\"https://www.facebook.com/ARADeveloper.ir\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-s-facebook\"");

WriteLiteral("></i></a></li>\r\n            <li><a");

WriteLiteral(" href=\"https://www.instagram.com/aradeveloper/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-s-instagrem\"");

WriteLiteral("></i></a></li>\r\n            <li><a");

WriteLiteral(" href=\"https://telegram.me/Aradeveloper\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon socicon-telegram\"");

WriteLiteral("></i></a></li>\r\n        </ul>\r\n    </div>\r\n    <!-- /.widget -->\r\n</div>");

        }
    }
}
#pragma warning restore 1591
