#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using ControlPannel;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administration/Views/Account/ConfirmEmail.cshtml")]
    public partial class _Areas_Administration_Views_Account_ConfirmEmail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Administration_Views_Account_ConfirmEmail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Administration\Views\Account\ConfirmEmail.cshtml"
  
    Layout = "~/Views/Themes/Admin/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        فعال سازی حساب کاربری\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n        <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">\r\n            با تشکر از عضویت شما در سایت. حساب شما با موفقیت فعال شد. برای ورو" +
"د به حساب خود کلیک کنید\r\n        </p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Areas\Administration\Views\Account\ConfirmEmail.cshtml"
   Write(Html.ActionLink("ورود به حساب", PaMVC.Administration.Account.ActionNames.Login, PaMVC.Administration.Account.Name,
        routeValues: new { area = "" }, htmlAttributes: new { @class = "btn btn-block btn-md btn-success" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
