#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using CommonInfoPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteInfo/Views/AdminSiteInfo/SiteInfo.cshtml")]
    public partial class _Areas_SiteInfo_Views_AdminSiteInfo_SiteInfo_cshtml : System.Web.Mvc.WebViewPage<AradCms.Core.ViewModel.Site.AddOrUpdateSiteInfo>
    {
        public _Areas_SiteInfo_Views_AdminSiteInfo_SiteInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
  
    Layout = "~/Views/Themes/Admin/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral("><h6");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-point-up\"");

WriteLiteral("></i> اطلاعات وبسایت</h6></div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"alert alert-success fade in block-inner\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close right\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(">×</button>\r\n            اطلاعات عمومی وبسایت در اینجا تنظیم میشود\r\n        </div" +
">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                <!-- Default pills -->\r\n                <span");

WriteLiteral(" class=\"subtitle right\"");

WriteLiteral(">اطلاعات عمومی</span>\r\n                <span");

WriteLiteral(" class=\"subtitle left\"");

WriteLiteral(">");

            
            #line 17 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                       Write(Html.ActionLink("ویرایش اطلاعات", InfMVC.SiteInfo.AdminSiteInfo.ActionNames.Edit, InfMVC.SiteInfo.AdminSiteInfo.Name, new { Id = 1, area = InfMVC.SiteInfo.Name }, new { title = "ویرایش" }));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <div");

WriteLiteral(" class=\"well block\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"tabbable\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"nav nav-pills\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#default-pill1\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">نام</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#default-pill2\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">درباره ما</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#default-pill3\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">تماس با ما</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#default-pill4\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">خدمات ما</a></li>\r\n                        </ul>\r\n                        <div");

WriteLiteral(" class=\"tab-content pill-content\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(" id=\"default-pill1\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" action=\"#\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 30 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                   Write(Html.LabelFor(a => Model.SiteName, new { @class = "col-sm-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" readonly=\"readonly\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2080), Tuple.Create("\"", 2103)
            
            #line 33 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                               , Tuple.Create(Tuple.Create("", 2088), Tuple.Create<System.Object, System.Int32>(Model.SiteName
            
            #line default
            #line hidden
, 2088), false)
);

WriteLiteral(">\r\n                                        </div>\r\n                              " +
"      </div>\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 37 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                   Write(Html.LabelFor(a => Model.SiteAddress, new { @class = "col-sm-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" readonly=\"readonly\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2554), Tuple.Create("\"", 2580)
            
            #line 40 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                               , Tuple.Create(Tuple.Create("", 2562), Tuple.Create<System.Object, System.Int32>(Model.SiteAddress
            
            #line default
            #line hidden
, 2562), false)
);

WriteLiteral(">\r\n                                        </div>\r\n                              " +
"      </div>\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 44 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                   Write(Html.LabelFor(a => Model.SitePhone, new { @class = "col-sm-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" readonly=\"readonly\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3029), Tuple.Create("\"", 3053)
            
            #line 47 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                               , Tuple.Create(Tuple.Create("", 3037), Tuple.Create<System.Object, System.Int32>(Model.SitePhone
            
            #line default
            #line hidden
, 3037), false)
);

WriteLiteral(">\r\n                                        </div>\r\n                              " +
"      </div>\r\n                                </div>\r\n                          " +
"  </div>\r\n                            <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"default-pill2\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" action=\"#\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 55 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                   Write(Html.LabelFor(a => Model.SiteAboute, new { @class = "col-sm-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 58 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                       Write(Html.Raw(Model.SiteAboute));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n                               " +
"     </div>\r\n                                </div>\r\n                           " +
" </div>\r\n                            <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"default-pill3\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" action=\"#\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 66 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                   Write(Html.LabelFor(a => Model.SiteContact, new { @class = "col-sm-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 69 "..\..\Areas\SiteInfo\Views\AdminSiteInfo\SiteInfo.cshtml"
                                       Write(Html.Raw(Model.SiteContact));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n                               " +
"     </div>\r\n                                </div>\r\n                           " +
" </div>\r\n                            <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"default-pill4\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" action=\"#\"");

WriteLiteral(@">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /default pills -->
            </div>
        </div>
    </div>
</div>");

        }
    }
}
#pragma warning restore 1591
