#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
    using AradCms.Core.Helpers;
    
    #line default
    #line hidden
    using ControlPannel;
    
    #line 2 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
    using ControlPannel.Areas.Administration.Views.RazorHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administration/Views/Role/Edit.cshtml")]
    public partial class _Areas_Administration_Views_Role_Edit_cshtml : System.Web.Mvc.WebViewPage<AradCms.Core.ViewModel.Role.EditRoleViewModel>
    {
        public _Areas_Administration_Views_Role_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
  
    ViewBag.Title = "ویرایش گروه کاربری کاربری";
    Layout = "~/Views/Themes/Admin/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                 using (Html.BeginForm(PaMVC.Administration.Role.ActionNames.Delete, PaMVC.Administration.Role.Name, new { area = PaMVC.Administration.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplate = "off", id = "deleteRoleForm" }))
                {
                    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                                            
                    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
               Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                                              

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'deleteRoleForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(">\r\n                                حذف گروه کاربری\r\n                            <" +
"/button>\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 23 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 30 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
         using (Html.BeginForm(PaMVC.Administration.Role.ActionNames.Edit, PaMVC.Administration.Role.Name, new { area = PaMVC.Administration.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "editRoleForm" }))
        {
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
       Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>مشخصات گروه</strong>\r\n                </div>\r\n    " +
"            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 40 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                   Write(Html.LabelFor(a => a.Name, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 42 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.NoAutoCompleteTextBoxFor(a => a.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 43 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.ValidationMessageFor(a => a.Name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                   Write(Html.LabelFor(a => a.Description, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.NoAutoCompleteTextBoxFor(a => a.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 50 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.ValidationMessageFor(a => a.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-2 col-md-offset-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(a => a.IsActive, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 56 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(a => a.IsActive, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 59 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(a => a.IsDefaultForRegister, new { @class = "checkbox-inline", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 60 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(a => a.IsDefaultForRegister, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 63 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(a => a.IsSystemRole, new { @class = "checkbox-inline", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 64 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(a => a.IsSystemRole, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>دسترسی ها</strong>\r\n                </div>\r\n      " +
"          <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 74 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
               Write(CheckBoxListBuilder.CheckBoxList("PermissionIds", ViewBag.Permissions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'editRoleForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                                ذخیره تغییرات\r\n                            </b" +
"utton>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </div>\r\n            </div>\r\n");

            
            #line 86 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 90 "..\..\Areas\Administration\Views\Role\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
