#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using FormPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/FormPlug/Views/OrderForm/List.cshtml")]
    public partial class _Areas_FormPlug_Views_OrderForm_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<FormPlugin.ViewModel.DataTableOrderForm>>
    {
        public _Areas_FormPlug_Views_OrderForm_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
  
    ViewBag.Title = "List";
    Layout = "~/Areas/Administration/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- Default table -->\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral("><h6");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-table2\"");

WriteLiteral("></i> پست های وبسایت</h6></div>\r\n    <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th>#</th>
                    <th>موضوع</th>
                    <th>نام/نام خانوادگی</th>
                    <th>موسسه/شرکت</th>
                    <th>وضعیت فرم</th>
                    <th>شماره همراه</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
");

            
            #line 23 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                 if (Model != null)
                {
                    foreach (var item in Model)
                    {


            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 29 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                           Write(Html.DisplayFor(a => item.Id));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 30 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                           Write(Html.DisplayFor(a => item.Subject));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 31 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                           Write(Html.DisplayFor(a => item.Name));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 32 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                           Write(Html.DisplayFor(a => item.Company));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 33 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                           Write(Html.DisplayFor(a => item.Status));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 34 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
                           Write(Html.DisplayFor(a => item.Phone));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n                            <td>\r\n\r\n                                <but" +
"ton");

WriteLiteral(" class=\"btn btn-danger \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1479), Tuple.Create("\"", 1503)
, Tuple.Create(Tuple.Create("", 1489), Tuple.Create("Edit(", 1489), true)
            
            #line 38 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
, Tuple.Create(Tuple.Create("", 1494), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 1494), false)
, Tuple.Create(Tuple.Create("", 1502), Tuple.Create(")", 1502), true)
);

WriteLiteral(">ویرایش<i");

WriteLiteral(" class=\"icon-trash \"");

WriteLiteral("></i></button>\r\n                                <button");

WriteLiteral(" class=\"btn btn-danger \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1612), Tuple.Create("\"", 1638)
, Tuple.Create(Tuple.Create("", 1622), Tuple.Create("Delete(", 1622), true)
            
            #line 39 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"
, Tuple.Create(Tuple.Create("", 1629), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 1629), false)
, Tuple.Create(Tuple.Create("", 1637), Tuple.Create(")", 1637), true)
);

WriteLiteral(">حذف<i");

WriteLiteral(" class=\"icon-trash \"");

WriteLiteral("></i></button>\r\n                            </td>\r\n                        </tr>\r" +
"\n");

            
            #line 42 "..\..\Areas\FormPlug\Views\OrderForm\List.cshtml"

                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>\r\n<!-- /default table -" +
"->\r\n<div");

WriteLiteral(" class=\"modal fade bs-example-modal-lg\"");

WriteLiteral(" id=\"myModal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">Modal title</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" id=\"bodymodal\"");

WriteLiteral(">\r\n                ...\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral(@"

    <script>
        function Delete(id) {

            $.ajax({
                url: ""/FormPlug/OrderForm/Delete/"" + id,
                type: ""Get"",
                data: {}
            }).done(function (result) {
                $(""#myModal"").modal('show');
                $(""#myModalLabel"").html('حذف');
                $(""#bodymodal"").html(result);

            });
        }
        function Edit(id) {

            $.ajax({
                url: ""/FormPlug/OrderForm/Edit/"" + id,
                type: ""Get"",
                data: {}
            }).done(function (result) {
                $(""#myModal"").modal('show');
                $(""#myModalLabel"").html('ویرایش');
                $(""#bodymodal"").html(result);

            });
        }
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
