#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using BlogPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Blog/Views/Widget/AddComent.cshtml")]
    public partial class _Areas_Blog_Views_Widget_AddComent_cshtml : System.Web.Mvc.WebViewPage<BlogPlugin.Models.PostComment>
    {
        public _Areas_Blog_Views_Widget_AddComent_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"comment-form-wrapper\"");

WriteLiteral(">\r\n    <h3>نظرتان را در مورد این مطلب با دیگران در میان بگذارید</h3>\r\n    <p>\r\n  " +
"      آدرس ایمیل شما منتشر نخواهد شد. زمینه های مورد نیاز مشخص شده اند\r\n        " +
"*\r\n    </p>\r\n");

            
            #line 8 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
     using (Html.BeginForm(BMVC.Blog.Widget.ActionNames.AddComent, BMVC.Blog.Widget.Name, new { area = BMVC.Blog.Name }, FormMethod.Post, new { role = "form", @class = "comment-form", autocomplete = "off", id = "addcomment", enctype = "multipart/form-data" }))
    {
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"name-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
       Write(Html.TextBoxFor(a => a.Author, new { @placeholder = "نام*" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
       Write(Html.ValidationMessageFor(m => m.Author, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"email-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
       Write(Html.TextBoxFor(a => a.Email, new { @placeholder = "ایمیل*" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
       Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 19 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"message-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
       Write(Html.TextAreaFor(a => a.Body, new { @rows = "5", @cols = "30", @placeholder = "نظر خود را اینجا وارد کنید...*" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
       Write(Html.ValidationMessageFor(m => m.Body, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ثبت\"");

WriteLiteral(" name=\"submit\"");

WriteLiteral(" class=\"btn btn-submit\"");

WriteLiteral(" />\r\n");

            
            #line 25 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Areas\Blog\Views\Widget\AddComent.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
