#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using BlogPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Blog/Views/Widget/GetBlogFooter.cshtml")]
    public partial class _Areas_Blog_Views_Widget_GetBlogFooter_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<BlogPlugin.ViewModel.DataTablePost>>
    {
        public _Areas_Blog_Views_Widget_GetBlogFooter_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
 if (Model != null)
{


            
            #line default
            #line hidden
WriteLiteral("    <ul");

WriteLiteral(" id=\"slider23\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
         foreach (var item in Model)
        {


            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"panel4\"");

WriteLiteral(">\r\n                <div>\r\n                    <div");

WriteLiteral(" class=\"textSlide\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 295), Tuple.Create("\"", 420)
            
            #line 16 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
, Tuple.Create(Tuple.Create("", 302), Tuple.Create<System.Object, System.Int32>(Url.Action(BMVC.Blog.Widget.ActionNames.Detailes, BMVC.Blog.Widget.Name, new { Id = item.Id, area = BMVC.Blog.Name })
            
            #line default
            #line hidden
, 302), false)
);

WriteLiteral(">>\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 457), Tuple.Create("\"", 503)
, Tuple.Create(Tuple.Create("", 463), Tuple.Create<System.Object, System.Int32>(Href("~/Uploads/SiteMedia/Post/")
, 463), false)
            
            #line 17 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
, Tuple.Create(Tuple.Create("", 488), Tuple.Create<System.Object, System.Int32>(item.PostImage
            
            #line default
            #line hidden
, 488), false)
);

WriteLiteral(" alt=\"tomato sandwich\"");

WriteLiteral(" />\r\n                            <h3>");

            
            #line 18 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
                           Write(Html.DisplayFor(a => item.Title));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                            <h4>");

            
            #line 19 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"
                           Write(Html.Raw(item.Summary));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                        </a>\r\n                    </div>\r\n                " +
"</div>\r\n            </li>\r\n");

            
            #line 24 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"

        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");

            
            #line 27 "..\..\Areas\Blog\Views\Widget\GetBlogFooter.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
