#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AradCms.Core.Helpers;
    using BlogPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Blog/Views/Widget/GetComments.cshtml")]
    public partial class _Areas_Blog_Views_Widget_GetComments_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<BlogPlugin.Models.PostComment>>
    {
        public _Areas_Blog_Views_Widget_GetComments_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"comments\"");

WriteLiteral(">\r\n\r\n        <ol");

WriteLiteral(" id=\"singlecomments\"");

WriteLiteral(" class=\"commentlist\"");

WriteLiteral(">\r\n");

            
            #line 7 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
            
            
            #line default
            #line hidden
            
            #line 7 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
             foreach (var item in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <div");

WriteLiteral(" class=\"user\"");

WriteLiteral("><img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 284), Tuple.Create("\"", 318)
, Tuple.Create(Tuple.Create("", 290), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Loom/images/u1.jpg")
, 290), false)
);

WriteLiteral(" class=\"avatar\"");

WriteLiteral(" /></div>\r\n                    <div");

WriteLiteral(" class=\"message\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"arrow-box\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n                                <h2>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 16 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
                                   Write(Html.DisplayFor(a => item.Author));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n                                </h2>" +
"\r\n                                <div");

WriteLiteral(" class=\"meta\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"date\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
                                                                 Write(Html.ConvertToPersianDateTime(item.CreatedOn));

            
            #line default
            #line hidden
WriteLiteral("</span> <span");

WriteLiteral(" class=\"reply\"");

WriteLiteral("><a");

WriteLiteral(" class=\"reply-link\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">پاسخ</a></span> </div>\r\n                            </div>\r\n                    " +
"        <p>");

            
            #line 21 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
                          Write(Html.DisplayFor(a => item.Body));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        </div>\r\n                    </div>\r\n               " +
" </li>\r\n");

            
            #line 25 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ol>\r\n    </div>\r\n");

            
            #line 28 "..\..\Areas\Blog\Views\Widget\GetComments.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
